FUNCTION = 'system.function'
COLLECTOR = 'system.collector'
WORKFLOW = 'system.workflow'
DESTINATION = 'system.destination'
LOGGER = 'system.logger'
PROPERTIES = 'system.event.properties'
EMBEDDINGS = 'system.ai.embeddings'