disposable_email_domains = {
    'fulvie.com', 'sanfinder.com', 'joseihorumon.info', 'bunsenhoneydew.com', 'pwrby.com',
    'wibblesmith.com', 'wxnw.net', 'fackme.gq', 'flurred.com', 'zoetropes.org', 'privy-mail.com',
    'mailme.ir', 'ldaho.biz', 'thichanthit.com', 'ginzi.net', 'f5.si', 'figurescoin.com', 'euaqa.com',
    'datazo.ca', 'mainerfolg.info', 'atnextmail.com', 'banit.club', 'maileimer.de', 'mailfree.ml',
    'ezstest.com', 'mygeoweb.info', 'nomail.cf', 'geew.ru', 'tafmail.com', 'crepeau12.com',
    'mailinator5.com', 'topmail2.com', 'ws.gy', 'ippandansei.tk', 'heathenhero.com', 'mailinator2.net',
    'guerrillamail.org', 'mail333.com', 'arduino.hk', 'siberpay.com', 'valemail.net',
    'willhackforfood.biz', 'net1mail.com', 'redfeathercrow.com', 'doublemail.de', 'mailonaut.com',
    'digitalmariachis.com', 'siliwangi.ga', 'wwjmp.com', 'deadchildren.org', 'buccalmassage.ru',
    'gynzy.eu', 'oborudovanieizturcii.ru', 'byebyemail.com', 'volaj.com', 'verdejo.com',
    'ephemeral.email', 'irabops.com', '0-mail.com', 'oing.cf', 'privacy.net', 'svip520.cn',
    'elitevipatlantamodels.com', 'disposableinbox.com', 'metadownload.org', 'symphonyresume.com',
    '99experts.com', 'facebookmail.gq', 'wellsfargocomcardholders.com', 'vomoto.com', 'kuhrap.com',
    'lolmail.biz', 'safetymail.info', 'veryrealemail.com', 'tempthe.net', 'theaviors.com', 'moakt.co',
    'wolfmail.ml', 'maildu.de', 'vercelli.cf', 'youneedmore.info', 'obobbo.com', 'maildrop.ml',
    'cl-cl.org', 'memsg.site', 'stop-my-spam.cf', 'eqiluxspam.ga', 'buffemail.com', 'vusra.com',
    'labworld.org', 'achievewe.us', 'tcwlx.com', 'cmail.com', 'esemay.com', 'lukecarriere.com',
    'ozyl.de', 'kpost.be', 'tapi.re', '4nextmail.com', 'bst-72.com', 'onemail.host', 'bum.net',
    'prin.be', 'technoproxy.ru', 'mailgutter.com', 'whaaaaaaaaaat.com', 'mailfa.tk', 'kappala.info',
    'eth2btc.info', 'email-fake.cf', 'tp-qa-mail.com', 'gynzy.gr', 'axiz.org', 'siftportal.ru',
    'spaml.com', 'onlineidea.info', 'spoofmail.de', 'thechildrensfocus.com', 'utiket.us',
    'silenceofthespam.com', 'freemeil.gq', 'tcwlm.com', '1zhuan.com', 'kino-100.ru', 'fr.cr',
    'duam.net', 'nowmymail.net', 'social-mailer.tk', 'budayationghoa.com', 'payspun.com',
    'chibakenma.ml', 'tokenmail.de', '6paq.com', 'wwwnew.eu', 'eveav.com', 'enayu.com',
    'widaryanto.info', 'giaiphapmuasam.com', 'mailjunk.gq', 'g3xmail.top', 'albionwe.us', 'msxd.com',
    'doiea.com', 'bauwerke-online.com', 'inbax.tk', 'btcmail.pw', 'just-email.com',
    'incognitomail.org', 'etranquil.org', 'reliable-mail.com', 'fitnesrezink.ru', 'resgedvgfed.tk',
    'binka.me', 'courriel.fr.nf', 'zv68.com', 'hackersquad.tk', 'oreidresume.com', 'cooh-2.site',
    'fightallspam.com', 'ether123.net', 'dontreg.com', 'top101.de', 'emailondeck.com', 'mywrld.top',
    'scay.net', 'discardmail.com', 'disposablemails.com', 'cyber-innovation.club', 'bnote.com',
    '5x25.com', 'opwebw.com', 'suexamplesb.com', 'riski.cf', 'cool.fr.nf', 'antispammail.de',
    'failbone.com', 'gett.icu', 'je-recycle.info', 'trashinbox.com', 'minsmail.com', 'gynzy.lt',
    'soodomail.com', '12houremail.com', 'regbypass.com', 'cl0ne.net', 'timkassouf.com',
    '10minutemail.co.uk', 'dispostable.com', 'armyspy.com', 'thespamfather.com', 'chielo.com',
    'qvy.me', 'grandmasmail.com', 'e-marketstore.ru', 'poehali-otdihat.ru', 'solar-impact.pro',
    'ternaklele.ga', '10mail.org', '0845.ru', 'indieclad.com', 'nabuma.com', 'quadrafit.com',
    'blogspam.ro', 'tmpemails.com', 'inkomail.com', 'guerrillamail.biz', 'suckmyd.com', 'cupbest.com',
    'byom.de', 'hypenated-domain.com', 'tmail.com', 'txtadvertise.com', 'digdig.org', 'rvb.ro',
    'twocowmail.net', 'getairmail.gq', 'andreihusanu.ro', 'penisgoes.in', 'yannmail.win',
    'grandmamail.com', 'yroid.com', 'fakedemail.com', 'amplewe.us', 'zaktouni.fr', 'vmailing.info',
    'patonce.com', 'willselfdestruct.com', 'smallker.tk', 'analyticalwe.us', 'freeteenbums.com',
    'fun64.com', 'mwarner.org', 'nationalgardeningclub.com', 'civx.org', 'tmmbt.net', 'magamail.com',
    'pqoia.com', 'gmxmail.top', 'briggsmarcus.com', 'ghosttexter.de', 'beluckygame.com',
    'coffeetimer24.com', 'top-shop-tovar.ru', 'kisstwink.com', 'uhhu.ru', 'unids.com', 'incq.com',
    'nurfuerspam.de', 'freemail.ms', 'borged.com', 'chinamkm.com', 'freemails.cf', 'proxyparking.com',
    'tempinbox.co.uk', 'vddaz.com', 'dshfjdafd.cloud', 'yugasandrika.com', 'toomail.biz', 'slipry.net',
    'airmailbox.website', 'brasx.org', 'gowikifilms.com', 'domforfb8.tk', 'adwaterandstir.com',
    'procrackers.com', 'girlmail.win', '10minutemails.in', 'crazymailing.com', 'spamfree24.eu',
    'instaddr.win', 'brefmail.com', 'at.hm', 'dev-null.ga', 'domforfb19.tk', 'mailnesia.com',
    'unimark.org', '105kg.ru', 'dudmail.com', 'allaccesswe.us', 'gmx1mail.top', 'para2019.ru',
    'nbzmr.com', 'gufum.com', 'smellrear.com', 'psles.com', 'emailias.com', 'olimp-case.ru',
    'tonaeto.com', 'tempemail.biz', 'hot-mail.ga', 'razemail.com', 'viditag.com', 'mji.ro',
    'isdaq.com', 'visal007.tk', '99cows.com', 'spam.su', 'zzi.us', 'ishop2k.com', 'fast-email.info',
    'xmail.com', 'tic.ec', 'xwaretech.info', 'wegwerfmail.org', 'lortemail.dk', 'one2mail.info',
    'it7.ovh', 'fictionsite.com', 'gynzy.es', 'instance-email.com', '36ru.com', 'snece.com',
    'trash-mail.de', 'remote.li', 'niseko.be', 'nh3.ro', 'groupbuff.com', 'alfaceti.com',
    'trashmails.com', 'z86.ru', 'throwawaymail.com', 'disign-revelation.com', 'piki.si', 'onqin.com',
    'sofrge.com', 'rejectmail.com', '0815.su', 'helloricky.com', 'sperma.cf', 'ushijima1129.ga',
    'email-jetable.fr', 'flyspam.com', 'facebook-email.ga', 'hostguru.top', 'kyal.pl', 'eoffice.top',
    'efxs.ca', 'trashmailer.com', 'watchfull.net', 'fermaxxi.ru', 'meantinc.com', 'anonymbox.com',
    'fucknloveme.top', 'migmail.pl', 'allaroundwe.us', 'zdenka.net', 'klassmaster.net',
    'domforfb18.tk', 'incognitomail.net', 'bgtmail.com', 'freerubli.ru', 'trashmail.at', 'jnxjn.com',
    '10minutemail.cf', 'email1.pro', 'emailresort.com', 'gmal.com', 'ministry-of-silly-walks.de',
    'instaddr.uk', 'wpg.im', 'ujijima1129.gq', 'aegia.net', 'ctos.ch', 'heathenhammer.com',
    'amail.club', 'free-email.cf', 'extracurricularsociety.com', 'ez.lv', 'korona-nedvizhimosti.ru',
    'rupayamail.com', 'vubby.com', 'salmeow.tk', 'mail-now.top', 'wegwerf-email-addressen.de',
    'hostlaba.com', 'momentics.ru', 'ucupdong.ml', 'trickmail.net', 'killmail.com', 'jetable.com',
    'temp-mail.pp.ua', 'postonline.me', '30minutemail.com', 'domforfb29.tk', 'you-spam.com',
    'mailtechx.com', 'mbox.re', 'affiliatedwe.us', 'recode.me', 'yarnpedia.ga', 'ipoo.org', '9mail.cf',
    'mail.by', 'nokiamail.com', 'mebelnu.info', 'nowhere.org', 'smashmail.de', 'trash-mail.gq',
    'xcompress.com', 'muathegame.com', 'completegolfswing.com', 'einrot.com', 'yeezus.ru',
    'amelabs.com', 'nomail.pw', 'iencm.com', 'kinda.email', 'puttanamaiala.tk', 'egzones.com',
    'kopaka.net', 'jwork.ru', 'bspooky.com', '6mail.ga', 'ipsur.org', 'mail2rss.org',
    'academiccommunity.com', 'cu.cc', 'pecinan.org', 'kvhrr.com', 'emeil.ir', 'elki-mkzn.ru',
    'get-mail.ml', 'doojazz.com', 'pavilionx2.com', 'emailtemporar.ro', 'getairmail.cf',
    'spam-be-gone.com', 'mailsucker.net', 'steam-area.ru', 'estate-invest.fr', 'affordablewe.us',
    'defomail.com', 'email-fake.ga', 'burnthespam.info', 'abovewe.us', 'spamgourmet.org',
    'emailwarden.com', 'reallymymail.com', 'camping-grill.info', 'amplifywe.us', 'klassmaster.com',
    'bonobo.email', 'mama3.org', 'oolus.com', 'spamail.de', 'inggo.org', 'tempmail.us', 'cbair.com',
    'dndent.com', 'pro-tag.org', 'alliancewe.us', 'einrot.de', 'ayakamail.cf', 'mailhazard.us',
    'monadi.ml', 'vuiy.pw', 'sabrestlouis.com', 'ecolo-online.fr', 'disposemail.com', '7tags.com',
    'nomail.xl.cx', 'maildrop.cf', 'xojxe.com', 'aphlog.com', 'daemsteam.com', 'get1mail.com',
    'trashymail.com', 'internetkeno.com', 'enterto.com', 'tagmymedia.com', 'bestlistbase.com',
    'emkei.gq', 'etranquil.net', 'jetable.pp.ua', 'sast.ro', 'greensloth.com', 'kitnastar.com',
    'ironiebehindert.de', 'mail21.cc', 'tempmailo.com', 'insanumingeniumhomebrew.com', 'shortmail.net',
    'soodonims.com', 'emailtmp.com', 'catgroup.uk', 'venompen.com', 'powlearn.com', 'obfusko.com',
    'alloutwe.us', 'zipcad.com', 'cream.pink', '5gramos.com', 'xxlocanto.us', 'deadfake.ga', 'toon.ml',
    'eposta.work', 'vemomail.win', 'nwytg.net', 'attnetwork.com', 'reftoken.net', 'zehnminutenmail.de',
    'lazyinbox.com', '2chmail.net', 'cheaphub.net', 'mezimages.net', 'e4ward.com',
    'giacmosuaviet.info', 'rumgel.com', 'all-cats.ru', 'mailna.in', 'makemetheking.com', 'aliaswe.us',
    'monumentmail.com', 'syinxun.com', 'ip4.pp.ua', 'pancakemail.com', 'spamtroll.net', 'kkmail.be',
    'uacro.com', 'gs-arc.org', 'thoas.ru', 'tmail3.com', 'garasikita.pw', 'mm.my', 'coolandwacky.us',
    'turuma.com', 'tvchd.com', 'uooos.com', 'wronghead.com', 'nospam.ze.tc', 'contbay.com',
    'fastmitsubishi.com', 'cmail.org', 'beddly.com', 'alisongamel.com', 'hungpackage.com',
    'mailhub.pro', 'daabox.com', 'csh.ro', '20minutemail.com', 'mailinator.com', 'zipsendtest.com',
    'tempmail.de', 'shitmail.me', 'uu.gl', 'netmails.net', 'igg.biz', 'ado888.biz', 'dash-pads.com',
    'gregorygamel.net', 'wralawfirm.com', 'anthony-junkmail.com', 'swift10minutemail.com',
    'daily-email.com', 'conf.work', 'mailinator4.com', 'nyasan.com', 'ftpinc.ca', 'bbhost.us',
    'uwork4.us', 'affluentwe.us', 'fangoh.com', 'gynzy.ro', 'webmail24.top', 'yaqp.com', 'gamail.top',
    'pinehill-seattle.org', 'spamfree24.info', 'ligsb.com', 'twzhhq.online', 'wegwerfmail.net',
    'hamham.uk', 'lifebyfood.com', 'trash-mail.cf', 'z0d.eu', 'indomina.cf', 'imails.info',
    'fuirio.com', 'predatorrat.tk', 'svxr.org', 'streetwisemail.com', 'inmynetwork.tk', 'killmail.net',
    'speed.1s.fr', 'fuwari.be', 'ichigo.me', 'spamex.com', 's33db0x.com', 'stop-my-spam.com',
    'carsencyclopedia.com', 'shut.name', 'mailjunk.tk', 'bspamfree.org', 'newmail.top', 'badpotato.tk',
    'cfo2go.ro', 'pig.pp.ua', 'blackmarket.to', 'mailosaur.net', '99.com', 'mailsac.com', 'xzsok.com',
    'clonemoi.tk', 'banit.me', '0815.ry', 'shalar.net', 'bookthemmore.com', 'mjj.edu.ge',
    'fakeinbox.com', 'newideasfornewpeople.info', 'alivance.com', 'alpha-web.net', 'tempr.email',
    'co.cc', 'mrvpm.net', 'iubridge.com', 'migumail.com', 'nincsmail.com', 'ama-trans.de',
    'wakingupesther.com', 'adobeccepdm.com', 'oopi.org', 'lovemeet.faith', 'inkiny.com',
    'tempmailer.de', 'xxhamsterxx.ga', 'pjjkp.com', 'drivetagdev.com', 'ige.es', 'minimail.gq',
    'electro.mn', 'qipmail.net', 'sueshaw.com', 'mailna.co', 'miauj.com', '4warding.net', '2wc.info',
    'ahk.jp', 'lovemeleaveme.com', 'sexyalwasmi.top', 'lordsofts.com', 'iroid.com', 'nicknassar.com',
    'foreastate.com', 'matra.site', 'bione.co', 'ppetw.com', 'hacccc.com', 'pratikmail.net', 'f4k.es',
    'moreorcs.com', 'ctmailing.us', 'dozvon-spb.ru', 'adoniswe.us', 'ycare.de', 'mycleaninbox.net',
    'bearsarefuzzy.com', 'thxmate.com', 'visal168.tk', 'aheadwe.us', 'nnoway.ru', 'poopiebutt.club',
    '2prong.com', 'gsxstring.ga', 'ldop.com', 'shhuut.org', 'newbpotato.tk', 'spamcero.com',
    'lacedmail.com', '6mail.cf', 'emailspam.ga', '5july.org', 'ericjohnson.ml', 'kekita.com',
    'lain.ch', 'randomail.net', 'shippingterms.org', 'packiu.com', 'popcornfarm7.com', 'uorak.com',
    'voidbay.com', 'sizzlemctwizzle.com', 'prtz.eu', '247web.net', 'airsi.de', 'zain.site',
    'throwawaymail.pp.ua', 'lukop.dk', 'sandcars.net', '027168.com', 'fexbox.org', 'email-fake.tk',
    'hazelnut4u.com', 'fakemail.fr', 'moakt.cc', 'zaym-zaym.ru', 'chong-mail.com', 'jellow.ml',
    'ny7.me', 'zoaxe.com', 'tempymail.com', 'dicopto.com', 'olypmall.ru', 'plexfirm.com', 'vipxm.net',
    'hellodream.mobi', 'viewcastmedia.org', 'meltedbrownies.com', 'bestsoundeffects.com',
    'intopwa.com', 'avls.pt', 'ls-server.ru', 'comwest.de', 'wegwrfmail.net', 'cnew.ir', 'top1mail.ru',
    'trashmail.gq', 'viewcastmedia.net', 'foxtrotter.info', 'mail707.com', 'cobarekyo1.ml', 'wsym.de',
    'dea-21olympic.com', 'bestchoiceusedcar.com', 'fastacura.com', 'upozowac.info', 'mailchop.com',
    'tensi.org', 'sinnlos-mail.de', 'muehlacker.tk', 'betr.co', 'disposable.site', 'instaddr.ch',
    'mailinator2.com', 'sendnow.win', 'kamsg.com', 'karatraman.ml', 'akerd.com', 'binnary.com',
    'victime.ninja', 'emailspam.gq', 'thatim.info', 'mailpooch.com', 'votiputox.org', 'mail72.com',
    'btc.email', 'haltospam.com', 'msrc.ml', 'login-email.ga', 'der-kombi.de', 'davidkoh.net',
    'bbitq.com', 'grugrug.ru', 'recursor.net', 'stop-my-spam.pp.ua', '15qm.com', 'neko2.net',
    'vankin.de', 'ginzi.be', 'hs.vc', 'mailcat.biz', 'fextemp.com', 'spambob.com', 'rax.la',
    'guerillamailblock.com', 'wiemei.com', 'acornwe.us', '2odem.com', 'coldemail.info',
    'mailinator.co.uk', '675hosting.net', 'yordanmail.cf', 'advisorwe.us', 'tropicalbass.info',
    'ycn.ro', 'dishcatfish.com', 'edgex.ru', 'svk.jp', 'zfymail.com', 'recipeforfailure.com',
    'manifestgenerator.com', 'centermail.com', 'aelo.es', 'spruzme.com', 'mailmoat.com', 'foxja.com',
    'idx4.com', 'placebomail10.com', 'spamcowboy.com', 'spindl-e.com', 'spambox.me', 'xcode.ro',
    'myspamless.com', 'mfsa.ru', 'raetp9.com', 'adventwe.us', 'itunesgiftcodegenerator.com',
    'bigstring.com', 'solventtrap.wiki', 'webm4il.info', 'kpay.be', 'spambob.org', 'absolutewe.us',
    'rejo.technology', 'mjukglass.nu', 'herp.in', 'itcompu.com', 'kbox.li', 'honeys.be',
    'ubismail.net', 'psnator.com', '1clck2.com', 'xcodes.net', 'cetpass.com', 'malahov.de', '1mail.ml',
    'dacoolest.com', 'rippb.com', 'rustydoor.com', 'mailproxsy.com', 'belamail.org', 'moneypipe.net',
    'hushmail.cf', 'fuwamofu.com', 'fastyamaha.com', 'bund.us', 'starlight-breaker.net', 'kmail.li',
    'kosmetik-obatkuat.com', 'awatum.de', 'pingir.com', 'emailportal.info', 'safersignup.de',
    'trashmail.ws', 'free-email.ga', 'midcoastcustoms.com', 'mailtemporaire.fr', 'pamaweb.com',
    'goonby.com', 'inboxproxy.com', 'spr.io', 'wokcy.com', 'apkmd.com', 'xvx.us', 'jungkamushukum.com',
    'beefmilk.com', 'mail-hub.info', 'vkcode.ru', 'mailinatar.com', 'go2vpn.net', 'autotwollow.com',
    'safermail.info', 'inboxalias.com', 'emailage.gq', 'themegreview.com', 'domforfb1.tk', 'kvhrw.com',
    'vercelli.gq', 'nonspam.eu', 'anappfor.com', 'fakeinformation.com', 'xkx.me', 'm21.cc',
    'msgos.com', 'chenbot.email', '2012-2016.ru', 'dev-null.cf', 'go2usa.info', '1chuan.com',
    'spambox.us', 'disposable.cf', 'midlertidig.com', 'secure-mail.cc', 'awsoo.com', 'larisia.com',
    'ieatspam.eu', 'emailsensei.com', 'rtrtr.com', 'vidchart.com', 'spamfighter.cf', 'statiix.com',
    'noicd.com', 'jiooq.com', 'duk33.com', 'kon42.com', 'petrzilka.net', 'youremail.cf',
    'mintemail.com', 'plhk.ru', 'aligamel.com', 'antispam.de', 'projectcl.com', 'ksmtrck.tk',
    'steambot.net', 'guerillamail.com', 'muchomail.com', 'royandk.com', 'pratikmail.com',
    'pecinan.com', 'ixx.io', 'mailhz.me', 'domforfb9.tk', 'onekisspresave.com', 'developermail.com',
    'emstjzh.com', 'mydefipet.live', 'artman-conception.com', 'plw.me', 'yep.it', 'hatespam.org',
    'dotmsg.com', 'thereddoors.online', 'mdhc.tk', 'geschent.biz', 'yahmail.top', 'gamgling.com',
    '12storage.com', 'cust.in', 'ambiancewe.us', 'revolvingdoorhoax.org', 'helpinghandtaxcenter.org',
    'cmail.net', 'mymailoasis.com', 'nezid.com', 'penoto.tk', 'liveradio.tk', 'o7i.net', '0x207.info',
    'academywe.us', 'inbox.si', 'eoopy.com', 'happy2023year.com', 'lindenbaumjapan.com',
    'myspaceinc.org', 'rma.ec', 'clickdeal.co', 'markmurfin.com', 'faecesmail.me', '10minutemail.net',
    'mailincubator.com', 'droplar.com', 'bitymails.us', 'email-fake.ml', 'zcrcd.com', 'ceed.se',
    'emkei.ml', 'sharkfaces.com', 'fast-mail.fr', 'discard.gq', 'thnikka.com', 'discard.ga',
    'daintly.com', 'spamwc.gq', 'hecat.es', 'upliftnow.com', 'dz17.net', 'demen.ml', 'trashmail.net',
    'nubescontrol.com', 'uma3.be', '5tb.in', 'eeedv.de', 'l33r.eu', 'lellno.gq',
    'garbagecollector.org', 'tempomail.org', 'getfun.men', 'mailfreeonline.com', 'jobbrett.com',
    'fivemail.de', 'spamsalad.in', 'stop-my-spam.ml', 'shopxda.com', 'storj99.top',
    'astroempires.info', 'gudanglowongan.com', 'sd3.in', 'xcoxc.com', 'hoanggiaanh.com', 'sfolkar.com',
    'sogetthis.com', 'thraml.com', 'cross-law.ga', 'mailimate.com', 'syosetu.gq', 'e-mail.com',
    'cashflow35.com', 'deadfake.tk', 'instmail.uk', 'chasefreedomactivate.com', 'ufacturing.com',
    '0v.ro', 'dharmatel.net', 'maswae.world', 'mailin8r.com', 'puppetmail.de', 'oepia.com', 'is.af',
    'mailfree.ga', 'nepwk.com', 'lopl.co.cc', 'ttirv.org', 'tmpeml.info', 'hiddentragedy.com',
    'deadfake.ml', 'fer-gabon.org', 'sdvgeft.com', 'mailme24.com', 'testore.co', 'veanlo.com',
    'intopwa.org', 'uguuchantele.com', 'emailsingularity.net', 'inoutmail.net', 'dumpyemail.com',
    'noref.in', 'griuc.schule', 'amberwe.us', 'badgerland.eu', 'drdrb.com', 'vrmtr.com', 'email60.com',
    'internetoftags.com', 'webhook.site', 'no-spam.ws', 'dob.jp', 'sroff.com', 'kzccv.com',
    'wegwerfemailadresse.com', 'thejoker5.com', 'secmail.pw', 'rootfest.net', 'vtxmail.us', 'spaml.de',
    'josse.ltd', 'emailthe.net', 'owlpic.com', 'nmail.cf', 'dawin.com', 'clrmail.com', 'dlemail.ru',
    'tempalias.com', 'koszmail.pl', 'fuckxxme.top', 'finews.biz', 'meltmail.com', 'ac20mail.in',
    'kaengu.ru', 'nutpa.net', 'dengekibunko.gq', 'mymail-in.net', 'piaa.me', 'pe.hu',
    'ashleyandrew.com', 'blnkt.net', 'mailback.com', 'notrnailinator.com', 'web-ideal.fr',
    'envy17.com', 'diolang.com', 'junk.to', 'dnses.ro', 'pixiil.com', 'irish2me.com', 'netmails.com',
    'pptrvv.com', 'freemails.ml', 'dealrek.com', 'gothere.biz', 'jaqis.com', 'derkombi.de',
    'trash-mail.com', 'mciek.com', 'mail1.top', 'lsyx24.com', 'guerrillamail.com', '10minutemail.com',
    'amicuswe.us', 'muell.icu', 'kartvelo.com', 'evopo.com', 'inoutmail.eu', 'shut.ws', 'storiqax.top',
    '10dk.email', 'despam.it', '10mail.tk', 'fexbox.ru', 'mailslapping.com', 'flemail.ru', 'dfgh.net',
    'soodmail.com', 'mailinator.net', 'gmial.com', 'kimsdisk.com', 'monemail.fr.nf', 'faithkills.com',
    'pagamenti.tk', 'tafoi.gr', 'spambob.net', 'hot-mail.tk', 'esbano-ru.ru', '3202.com',
    'spamfighter.ml', 'cnamed.com', 'mailzilla.org', 'trbvo.com', 'mailjunk.ga', 'fddns.ml',
    'antichef.com', 'popgx.com', 'emkei.ga', 'noblepioneer.com', 'remarkable.rocks',
    'best-john-boats.com', 'safetypost.de', 'tanukis.org', 'munoubengoshi.gq', 'powered.name',
    'byespm.com', 'keepmymail.com', 'lilspam.com', 'ze.tc', 'mierdamail.com', 'safaat.cf',
    '10minut.com.pl', 'femailtor.com', 'italy-mail.com', 'mailtv.net', 'mailforspam.com',
    'antispam24.de', 'emailtech.info', 'lakelivingstonrealestate.com', 'puji.pro', 'cek.pm',
    'gbcmail.win', 'rover.info', 'emlhub.com', 'spamgourmet.net', 'meruado.uk', 'nwytg.com',
    'thescrappermovie.com', 'getsimpleemail.com', 'givememail.club', 'whatpaas.com', 'zzrgg.com',
    'freeschoolgirlvids.com', 'mailmetrash.com', 'nobulk.com', 'cbes.net', 'hazmatshipping.org',
    'azazazatashkent.tk', 'okinawa.li', 'realquickemail.com', 'supergreatmail.com', 'tyldd.com',
    'thankyou2010.com', 'vmpanda.com', '5minutemail.net', 'tempmailer.net', 'walkmail.net',
    'netris.net', 'myphantomemail.com', 'affiliate-nebenjob.info', 'wifioak.com', '123-m.com',
    'magicbox.ro', 'simaenaga.com', 'mailinator3.com', 'indirect.ws', 'mentonit.net', 'trash2011.com',
    'loan101.pro', 'snakebutt.com', 'emailfake.com', 'pepbot.com', 'cachedot.net', 'oosln.com',
    'peterdethier.com', 'domozmail.com', 'gdmail.top', 'freeblackbootytube.com', 'bio-muesli.net',
    'getairmail.tk', 'kadokawa.ga', 'seekapps.com', 'wemel.top', 'domforfb2.tk', 'makemenaughty.club',
    'one-mail.top', '672643.net', 'gosuslugi-spravka.ru', 'neomailbox.com', 'oalsp.com', 'qisdo.com',
    'asdasd.ru', 'ttszuo.xyz', 'p33.org', 'zemzar.net', 'o2stk.org', 'proxymail.eu', 'spamarrest.com',
    'server.ms', 'mailrock.biz', 'keinhirn.de', 'ownsyou.de', 'foreskin.cf', 'startkeys.com',
    'uemail99.com', 'vikingsonly.com', 'mox.pp.ua', 'sikux.com', 'mucincanon.com', 'ytpayy.com',
    'headstrong.de', 'whatsaas.com', 'chatich.com', 'fragolina2.tk', 'discard.tk', '20mm.eu', 'bot.nu',
    'disposeamail.com', 'ind.st', 'iwi.net', 'gynzy.pl', 'midcoastcustoms.net', 'spamfree24.org',
    'mail-easy.fr', 'laoeq.com', 'allthegoodnamesaretaken.org', 'cavi.mx', 'dandikmail.com',
    'gregorsky.zone', 'kkoup.com', 'getairmail.ga', 'emailxfer.com', 'divermail.com', '55hosting.net',
    'pitaniezdorovie.ru', 'casualdx.com', 'xww.ro', 'used-product.fr', 'klovenode.com', 'gexik.com',
    'mutant.me', 'sackboii.com', 'ginzi.es', 'kulmeo.com', 'forecastertests.com', 'bio-muesli.info',
    'greencafe24.com', 'incognitomail.com', 'dayrep.com', 'midcoastsolutions.net', 'nowmymail.com',
    'arurgitu.gq', 'stexsy.com', 'nullbox.info', 'usa.cc', 'inpwa.com', 'yomail.info',
    'alina-schiesser.ch', 'beribase.ru', 'kobrandly.com', 'zepp.dk', 'dengekibunko.ml', 'deagot.com',
    'trixtrux1.ru', 'idxue.com', 'lags.us', 'lyfestylecreditsolutions.com', 'vintomaper.com',
    'mofu.be', '42o.org', 'zippymail.info', 'urfunktion.se', '14n.co.uk', 'yopmail.fr',
    'smapfree24.info', 'mailbox92.biz', 'dodsi.com', 'mailtraps.com', 'hairs24.ru',
    'durandinterstellar.com', 'miucce.com', 'myspacepimpedup.com', 'mail1web.org', 'webuser.in',
    'advocatewe.us', 'widget.gg', 'mailna.biz', 'anonymized.org', 'tmpmail.net',
    'freebabysittercam.com', 'al-qaeda.us', 'get.pp.ua', 'koshu.ru', 'trashdevil.de', 'temp-mail.de',
    'i6.cloudns.cc', '50set.ru', 'mail22.club', 'morriesworld.ml', 'shrib.com', 'mailslite.com',
    'xn--d-bga.net', 'malayalamdtp.com', '1ce.us', 'azcomputerworks.com', 'sluteen.com', 'wollan.info',
    'adfskj.com', 'securehost.com.es', '5mail.ga', 'adventurewe.us', '5oz.ru', 'hostcalls.com',
    'blip.ch', 'chitthi.in', 'rapt.be', 'alph.wtf', '4k5.net', 'slippery.email', '10-minute-mail.com',
    'eml.pp.ua', 'vsimcard.com', 'ginzy.co.uk', 'mail-temporaire.com', 'mail-filter.com',
    'bundes-li.ga', 'm4ilweb.info', 'delayload.net', 'rkomo.com', 'rbb.org', 'hpc.tw', 'l-c-a.us',
    'snapwet.com', 'acucre.com', 'sika3.com', '6ip.us', 'ver0.ml', 'theteastory.info',
    'norseforce.com', 'wuzup.net', 'xy9ce.tk', 'thedirhq.info', 'qq.my', 'tmpjr.me', '0wnd.net',
    'filberts4u.com', 'trollproject.com', 'imgof.com', 'raqid.com', 'buspad.org', 'emails.ga',
    'loadby.us', 'wegwerfadresse.de', 'eatmea2z.club', 'sinfiltro.cl', 'mykickassideas.com',
    'mohmal.im', 'spamspot.com', 'yourtube.ml', 'spambog.ru', 'sute.jp', 'b2cmail.de', 'any.pink',
    'gynzi.es', 'one-time.email', 'sjuaq.com', 'mechanicalresumes.com', 'dodgeit.com', 'emailfake.ml',
    'maildrop.gq', 'fastnissan.com', 'rifkian.ga', 'ushijima1129.ml', 'analysiswe.us',
    'gowikitravel.com', 'anit.ro', 'acrossgracealley.com', '1000rebates.stream', 'g14l71lb.com',
    'lez.se', 'pachilly.com', 'pfui.ru', 'sportrid.com', 'dev-null.ml', 'zoemail.net', 'cubiclink.com',
    'ansibleemail.com', 'honor-8.com', 'naslazhdai.ru', 'unit7lahaina.com', 'maileater.com',
    'geldwaschmaschine.de', 'nospam4.us', 'vnedu.me', 'nonspammer.de', 'stylist-volos.ru',
    'wegwerpmailadres.nl', 'ixaks.com', 'omtecha.com', 'spikio.com', 'spambox.info', 'emkei.tk',
    'tympe.net', 'clearwatermail.info', 'fdfdsfds.com', 'thediamants.org', 'imstations.com',
    'selfdestructingmail.org', 'benipaula.org', 'yui.it', 'gehensiemirnichtaufdensack.de',
    'mailismagic.com', 'gardenscape.ca', 'inboxbear.com', 'uber-mail.com', 'altuswe.us', 'ovpn.to',
    'mailorc.com', 'seekjobs4u.com', 'macr2.com', 'le-tim.ru', 's0ny.net', 'adaptivewe.us',
    '10minutesmail.fr', 'tmailinator.com', 'nawmin.info', 'extremail.ru', 'weizixu.com', 'cutout.club',
    'kadokawa.ml', 'mailinator7.com', 'visal168.gq', 'tizi.com', 'lamasticots.com', 'katztube.com',
    'myindohome.services', 'spam.org.es', 'altitudewe.us', 'dhm.ro', 'realtyalerts.ca', 'altairwe.us',
    'desoz.com', 'teleworm.com', 'tmail.ws', 'curlhph.tk', 'larland.com', 'nnh.com', 'analogwe.us',
    'emailsy.info', 'link2mail.net', 'viewcastmedia.com', 'wetrainbayarea.org', 'daymailonline.com',
    'jetable.fr.nf', 'kellychibale-researchgroup-uct.com', 'oxopoha.com', 'tonne.to', 'vmani.com',
    'wuuvo.com', 'nothingtoseehere.ca', 'usbc.be', 'skyrt.de', 'mailexpire.com',
    'elearningjournal.org', 'nogmailspam.info', 'film-blog.biz', 'matamuasu.ga', 'gelitik.in',
    'emailsecurer.com', 'disposableemailaddresses.com', 'nguyenusedcars.com', 'tiv.cc', 'de-a.org',
    'cocoro.uk', 'tb-on-line.net', 'emil.com', 'air2token.com', 'hotmai.com', 'clandest.in',
    'tmpbox.net', 'diwaq.com', 'spamcon.org', 'tranceversal.com', 'existiert.net', 'gustr.com',
    'mail-hosting.co', 'ajaxapp.net', 'wickmail.net', 'supersave.net', 'd3p.dk', 'droolingfanboy.de',
    'evilcomputer.com', 'kennedy808.com', 'mailjunk.ml', 'thelimestones.com', 'indomaed.pw',
    '20email.eu', 'damnthespam.com', 'discos4.com', 'obxpestcontrol.com', 'adsd.org', 'boofx.com',
    'sinema.ml', 'ip6.pp.ua', 'pewpewpewpew.pw', 'mailinater.com', 'yabai-oppai.tk', 'inboxkitten.com',
    'inoutmail.de', 'dropsin.net', 'frwdmail.com', 'hotmial.com', 'undo.it', 'hoanglong.tech',
    'mailto.plus', 'shchiba.uk', 'add3000.pp.ua', 'klzlk.com', 'block521.com', 'kiani.com',
    'vixtricks.com', 'adroh.com', 'facebook-email.cf', 'lastmail.co', 'mymail90.com', 'gzb.ro',
    'trbvm.com', 'email.edu.pl', 'mytemp.email', 'emailisvalid.com', 'americasbestwe.us', 'vipmail.pw',
    'mailtome.de', 'garrymccooey.com', 'sofort-mail.de', 'hidzz.com', 'zhorachu.com', 'deinbox.com',
    'click-email.com', '1-tm.com', 'allgoodwe.us', 'buyordie.info', 'dildosfromspace.com',
    'abilitywe.us', 'bumpymail.com', 'drevo.si', 'uplipht.com', 'popcornfly.com', 'hmamail.com',
    'superplatyna.com', 'mail1a.de', 'thex.ro', 'webcontact-france.eu', 'rabin.ca', 'hawrong.com',
    'internet-v-stavropole.ru', 'fettometern.com', '1secmail.net', 'lr7.us', 'trashmail.io',
    'get2mail.fr', 'fir.hk', 'nm7.cc', 'thisisnotmyrealemail.com', 'sendingspecialflyers.com',
    'budaya-tionghoa.com', 'trasz.com', 'emailnax.com', 'zebins.com', 'boximail.com', 'inoutmail.info',
    'esc.la', 'temporary-mail.net', 'solvemail.info', 'h8s.org', 'fbma.tk', 'spamwc.ml',
    'gnctr-calgary.com', 'isukrainestillacountry.com', 'pivo-bar.ru', 'spamfighter.tk',
    'gixenmixen.com', 'shitaway.tk', 'linuxmail.so', 'spamfree24.com', 'yahooproduct.net', 'dp76.com',
    'wimsg.com', 'inactivemachine.com', 'fizmail.com', 'deadaddress.com', 'discard.ml', '1secmail.com',
    'grr.la', 'ushijima1129.tk', 'spacebazzar.ru', 'tonymanso.com', 'aschenbrandt.net', 'tellos.xyz',
    'insorg-mail.info', 'nyrmusic.com', 'dropcake.de', 'losemymail.com', '30wave.com',
    'augmentationtechnology.com', 'loaoa.com', 'yopmail.gq', 'justemail.ml', 'adubiz.info',
    'payperex2.com', 'freesistercam.com', 'ddcrew.com', 'turoid.com', 'b2bx.net', 'soisz.com',
    'anotherdomaincyka.tk', 'bestoption25.club', 'front14.org', 'tipsb.com', 'xwaretech.com',
    'spamfree.eu', 'disaq.com', 'hotpop.com', 'buyusdomain.com', 'spamlot.net',
    'simpleitsecurity.info', 'g2xmail.top', 'smellypotato.tk', 'xost.us', 'edv.to', 'socialfurry.org',
    'truthfinderlogin.com', 'stopspam.app', 'mailtothis.com', 'dyceroprojects.com', 'mansiondev.com',
    'spamcorptastic.com', 'mockmyid.com', 'pi.vu', 'theroyalweb.club', '21cn.com', 'dumpmail.de',
    'fr33mail.info', 'freeplumpervideos.com', 'zymuying.com', 'goemailgo.com', 'photomark.net',
    'qoika.com', 'tastrg.com', 'tempe-mail.com', 'zhaoqian.ninja', 'ldtp.com', 'correo.blogos.net',
    'inboxed.pw', 'porsh.net', 'wegwerfemail.info', 'haribu.com', 'jmail.ovh', 'delivrmail.com',
    'buymoreplays.com', 'lroid.com', 'fakemailgenerator.com', 'maildrop.cc', 'bootybay.de',
    '11163.com', 'shieldemail.com', 'findu.pl', 'fakemailz.com', 'moonwake.com', 'email-fake.gq',
    '2ether.net', 'tempmail.cn', 'zhaoyuanedu.cn', 'szerz.com', 'foreskin.ml', 'delikkt.de',
    'royaldoodles.org', 'autowb.com', 'satisfyme.club', 'ourklips.com', 'ee2.pl', '1pad.de',
    'spamfree24.de', 'great-host.in', 'tradermail.info', 'digital-message.com',
    'temporarioemail.com.br', 'veryday.ch', 'waterisgone.com', 'silvercoin.life', 'chewydonut.com',
    'darkharvestfilms.com', 'mailzi.ru', 'migmail.net', 'kaspop.com', 'mailfirst.icu',
    'harakirimail.com', 'j-p.us', 'xmailer.be', 'services391.com', 'vaasfc4.tk', 'cdpa.cc',
    'cloudns.cx', 'labetteraverouge.at', 'tryninja.io', 'geteit.com', 'coolimpool.org',
    'allemojikeyboard.com', 'spymail.one', 'xagloo.com', 'grish.de', 'rancidhome.net', '7mail.ml',
    'zoemail.org', 'fastchevy.com', 'shipfromto.com', 'freedompop.us', 'emkei.cf', 'amail4.me',
    '10minutemail.de', 'blackgoldagency.ru', 'bussitussi.com', 'glitch.sx', 'quickinbox.com',
    'humaility.com', 'wfgdfhj.tk', 'getairmail.com', 'fakeinbox.tk', 'childsavetrust.org',
    'midlertidig.org', 'spymail.com', 'douchelounge.com', 'slapsfromlastnight.com',
    'medkabinet-uzi.ru', 'spammy.host', 'abakiss.com', 'virtualemail.info', 'mailscrap.com',
    'nvhrw.com', 'spambog.net', 'whatifanalytics.com', 'hot-mail.gq', 'cringemonster.com',
    'antireg.com', 'emailage.cf', 'kwift.net', 'givmail.com', 'midlertidig.net', 'baxomale.ht.cx',
    'nomorespamemails.com', '80665.com', '5ghgfhfghfgh.tk', 'domforfb4.tk', 'easy-trash-mail.com',
    'spambooger.com', 'temporarymailaddress.com', 'bheps.com', 'my-pomsies.ru', 'xrap.de',
    'ofisher.net', 'giveh2o.info', 'loin.in', 'ephemail.net', 'throam.com', 'tmail9.com',
    'afrobacon.com', 'xemaps.com', 'berirabotay.ru', 'balaket.com', '6url.com', 'tempemail.com',
    'okclprojects.com', 'mailpluss.com', 'mailbox52.ga', 'beribaza.ru', 'remail.ga', 'wmail.cf',
    '24hinbox.com', 'junk1e.com', 'temporaryemail.us', 'boun.cr', 'brennendesreich.de', 'drmail.in',
    'trashymail.net', 'sofortmail.de', 'oneoffemail.com', 'arroisijewellery.com', 'cigar-auctions.com',
    'reptilegenetics.com', 'tutuapp.bid', 'nezzart.com', 'smarttalent.pw', 'sharklasers.com',
    'chammy.info', 'nomail2me.com', 'gorillaswithdirtyarmpits.com', 'muell.monster', 'vps30.com',
    'deekayen.us', '3d-painting.com', 'trashmail.org', 'rsvhr.com', 'molms.com', 'trash-mail.tk',
    'donebyngle.com', 'mtmdev.com', 'avia-tonic.fr', 'mailinator.us', 'a7996.com', 'vickaentb.tk',
    'wuespdj.xyz', 'evyush.com', 'orgmbx.cc', 'cutradition.com', 'fake-mail.cf', '10minutesmail.com',
    'moakt.ws', 'tdtda.com', 'freeml.net', 'cartelera.org', 'hahawrong.com', 'easynetwork.info',
    'fammix.com', 'moburl.com', 'starpower.space', 'swift-mail.net', 'super-auswahl.de', '0box.eu',
    'pokiemobile.com', 'rowe-solutions.com', 'mymaily.lol', 'wekawa.com', 'zainmax.net', '0w.ro',
    'wegwerfemail.de', 'hmail.us', '20mail.in', 'buzzcluby.com', 'shitmail.org', 'xbaby69.top',
    '1st-forms.com', 'fakeinbox.info', 'temp-link.net', 'techblast.ch', 'yoo.ro', 'get-mail.ga',
    'youmail.ga', 'ynmrealty.com', 'fadingemail.com', 'mailme.gq', 'mailzilla.com', 'yyolf.net',
    'wikidocuslava.ru', 'vipepe.com', 'irc.so', 'ass.pp.ua', 'kasmail.com', 'tempmaildemo.com',
    'yopmail.net', 'remail.cf', 'loh.pp.ua', 'krd.ag', 'tormail.org', 'rabiot.reisen', 'coza.ro',
    'hornyalwary.top', 'trashmail.me', 'tiapz.com', 'fakeinbox.ga', 'veryday.eu', 'mypacks.net',
    'hidemail.pro', 'mailnull.com', 'g4hdrop.us', 'abacuswe.us', 'freemeil.ml', 'domforfb3.tk',
    'hidemail.de', 'shipping-regulations.com', 'dontsendmespam.de', 'mailapp.top', 'yuoia.com',
    'motique.de', 'secretemail.de', 'testudine.com', 'negated.com', 'yermail.net', 'quickemail.info',
    'inboxclean.com', 'fansworldwide.de', 'bunchofidiots.com', 'courrieltemporaire.com', 'gotmail.com',
    'softpls.asia', 'metaintern.net', 'dbunker.com', '1to1mail.org', 'nada.ltd', 'frapmail.com',
    'gregorygamel.com', 'yogamaven.com', 'blogmyway.org', 'accreditedwe.us', 'aegde.com',
    'jdmadventures.com', 'smapfree24.de', 'wegwerf-email.net', 'acumenwe.us', 'spritzzone.de',
    'joetestalot.com', 'bbitj.com', 'maildx.com', 'drdrb.net', 'kiois.com', 'magim.be', 'gage.ga',
    'averdov.com', 'goplaygame.ru', 'freemails.ga', 'gowikicars.com', 'ntlhelp.net',
    'regbypass.comsafe-mail.net', 'aron.us', 'hi5.si', 'exelica.com', 'in2reach.com', 'wupics.com',
    'happydomik.ru', 'ieatspam.info', 'activitywe.us', 'mailhazard.com', 'hola.org', 'isosq.com',
    'clixser.com', 'friendlymail.co.uk', 'mailde.de', 'astonut.tk', 'uk.to', 'dcctb.com',
    'thecarinformation.com', 'choicemail1.com', 'freemeil.ga', 'herpderp.nl', 'ip6.li', 'itfast.net',
    'shadap.org', 'chong-mail.net', 'mozej.com', 'gamegregious.com', 'tempmail.co', 'epb.ro',
    'linkedintuts2016.pw', 'paharpurmim.ga', 'crusthost.com', 'maildrop.ga', 'chong-mail.org',
    'alphaomegawe.us', 'nextstopvalhalla.com', 'zzz.com', 'pookmail.com', 'cars2.club',
    'dotslashrage.com', 'interstats.org', 'spamfighter.ga', 'lee.mx', 'vda.ro', 'vercelli.ml',
    'emailspam.ml', 'squizzy.de', '4mail.cf', 'codeandscotch.com', 'fuwa.li', 'gowikitv.com',
    'nproxi.com', 'runi.ca', 'advantagewe.us', 'emeraldwebmail.com', '0n0ff.net', 'emaillime.com',
    'esgeneri.com', 'keipino.de', '20email.it', 'coinlink.club', 'opentrash.com',
    'sociallymediocre.com', 'accentwe.us', 'spamsandwich.com', 'shiphazmat.org', 'spamfellas.com',
    'us.to', 'mailbiscuit.com', 'cnsds.de', 'spamday.com', 'klipschx12.com', 'emailage.tk',
    'gmatch.org', 'freelance-france.eu', 'login-email.ml', 'fake-mail.ga', 'fakeinbox.ml',
    'dispomail.eu', 'etotvibor.ru', '1secmail.org', 'opendns.ro', 'songsign.com', 'consumerriot.com',
    'fornow.eu', 'sweetxxx.de', 'mailita.tk', 'mailna.me', 'emailz.cf', 'neverbox.com',
    '2fdgdfgdfgdf.tk', 'sexforswingers.com', 'rm2rf.com', 'yoggm.com', 'mailmoth.com', 'boatmail.us',
    'clipmail.eu', 'muell.xyz', 'prazdnik-37.ru', 'choco.la', 'toddsbighug.com', 'ver0.ga',
    'deyom.com', 'imail1.net', 'kaovo.com', 'chogmail.com', 'duskmail.com', 'objectmail.com',
    '4warding.org', 'junkmail.gq', 'sky-ts.de', 'doanart.com', '10minutemail.be',
    'wegwerf-email-adressen.de', 'writeme.us', '3l6.com', 'bluedumpling.info', 'explodemail.com',
    'mail4trash.com', 'email-fake.com', 'thanksnospam.info', '8mail.ml', 'bbitf.com', 'azmeil.tk',
    'greggamel.com', 'mark-compressoren.ru', 'ht.cx', 'grn.cc', 'fixmail.tk', 'emailfreedom.ml',
    'mobileninja.co.uk', 'theeyeoftruth.com', 'urhen.com', 'vpn.st', 'chilkat.com', 'fastkawasaki.com',
    'wazabi.club', 'dred.ru', 'joelpet.com', 'login-email.cf', 'schrott-email.de', 'tmpx.sa.com',
    'iaoss.com', 'stinkefinger.net', 'autosouvenir39.ru', 'yanet.me', 'foreskin.ga', 'qopow.com',
    'hochsitze.com', 'art-en-ligne.pro', 'mailbidon.com', 'teleg.eu', 'imul.info', 'dispo.in',
    'rfc822.org', 'flymail.tk', 'mystvpn.com', 'awdrt.org', 'chickenkiller.com', 'mail-help.net',
    'dropjar.com', 'tempmail.ws', 'jourrapide.com', 'nypato.com', 'thrubay.com', 'emailure.net',
    'tmpeml.com', 'spamobox.com', 'fxnxs.com', 'topinrock.cf', 'domforfb5.tk', 'online.ms',
    'emailinfive.com', 'mail.mezimages.net', 'investore.co', 'ereplyzy.com', 'sheryli.com',
    'spam.care', 'w-asertun.ru', 'badoop.com', 'mt2009.com', 'next.ovh', 'totallynotfake.net',
    'aditus.info', 'belljonestax.com', 'mspeciosa.com', 'nice-4u.com', 'mailbox80.biz', 'domforfb6.tk',
    'antichef.net', 'auti.st', 'triots.com', 'chaichuang.com', 'sonshi.cf', 'yamail.win', 'yodx.ro',
    'mailinator9.com', 'razuz.com', 'g1xmail.top', 'agger.ro', 'kemptvillebaseball.com', 'rppkn.com',
    'jafps.com', 'miaferrari.com', 'put2.net', 'onewaymail.com', '10minutemail.us', 'schmeissweg.tk',
    'locantowsite.club', 'ecallheandi.com', 'kommunity.biz', 'mobilevpn.top', 'statdvr.com',
    'yspend.com', 'litedrop.com', 'bsnow.net', 'usako.net', 'oshietechan.link', 'animesos.com',
    'cuvox.de', 'awiki.org', 'mailuniverse.co.uk', 'sin.cl', 'twkly.ml', 'allofthem.net',
    'freeinbox.email', '100likers.com', 'disposable.ga', 'empireanime.ga', 'octovie.com',
    'stanfordujjain.com', 'trashmail.com', 'cam4you.cc', '1fsdfdsfsdf.tk', 'ploae.com', 'gsrv.co.uk',
    'tverya.com', 'icx.in', 'amazon-aws.org', 'activatewe.us', 'a-bc.net', 'trash2009.com', '3mail.ga',
    'claimab.com', 'yourdomain.com', 'ama-trade.de', 'superstachel.de', 'blogos.net',
    'throwawayemailaddress.com', 'sdvrecft.com', 'yapped.net', 'maileme101.com', 'aegiswe.us',
    'stuckmail.com', 'besttempmail.com', 'trashcanmail.com', 'mailnator.com', 'anonmails.de',
    'freedom4you.info', 'netviewer-france.com', 'derluxuswagen.de', 'royalmarket.life', 'allstarwe.us',
    'brand-app.biz', 'ftp.sh', 'businesssuccessislifesuccess.com', 'twinmail.de', 'appc.se',
    'fexpost.com', 'farrse.co.uk', 'affilikingz.de', 'mail7.io', 'mailseal.de', 'syujob.accountants',
    'ihazspam.ca', 'trashemail.de', 'gowikicampus.com', 'inboxstore.me', 'agedmail.com',
    'bukhariansiddur.com', 'itsjiff.com', 'tagyourself.com', '10minutmail.pl', 'boxformail.in',
    'kadokawa.cf', 'mailbox82.biz', 'garbagemail.org', 'ruru.be', 'ultrada.ru', 'r4nd0m.de',
    'zarabotokdoma11.ru', 'facebookmail.ml', 'trialmail.de', 'lyricspad.net', 'greendike.com',
    'shotmail.ru', 'digitalmail.info', 'mailfall.com', 'nwldx.com', 'pojok.ml', 'walkmail.ru',
    'pokemail.net', 'spamcannon.com', 'mailjunk.cf', 'qwickmail.com', 'sohai.ml', 'nuts2trade.com',
    'maggotymeat.ga', 'locomodev.net', 'raxtest.com', '20mail.it', 'talkinator.com', 'nobugmail.com',
    'sofimail.com', 'gifto12.com', 'saeoil.com', 'krsw.tk', 'xcpy.com', 'trashmailgenerator.de',
    'mailme.lv', 'smwg.info', 'web2mailco.com', 'login-email.tk', 'emlpro.com', 'speedgaus.net',
    'kariplan.com', 'mijnhva.nl', 'kadokawa.tk', 'adpugh.org', 'dataarca.com', 'emailz.ga',
    'mailinator0.com', 'taphear.com', 'taukah.com', 'robot-mail.com', 'spambog.de', 'krypton.tk',
    'davidlcreative.com', 'emailmiser.com', 'inboxdesign.me', 'hotmailproduct.com', 'tpwlb.com',
    'tofeat.com', 'cocovpn.com', 'fatflap.com', 'domforfb27.tk', 'californiafitnessdeals.com',
    'myspaceinc.net', '0815.ru', 'eyepaste.com', 'xagloo.co', 'ronnierage.net', 'lakqs.com',
    'lolfreak.net', 'mannawo.com', 'myinfoinc.com', 'rosebearmylove.ru', 'startfu.com', 'tinoza.org',
    'winemaven.info', 'wierie.tk', 'arvato-community.de', 'qc.to', 'kmhow.com', 'mfsa.info',
    'sandelf.de', '10minutemail.pro', 'freundin.ru', 'nervmich.net', 'profast.top', 'kruay.com',
    'propscore.com', '1s.fr', 'emz.net', 'girlsundertheinfluence.com', 'yedi.org', 'mailbox87.de',
    'emailgo.de', 'netzidiot.de', 'jobbikszimpatizans.hu', 'esadverse.com', 'hat-geld.de',
    'lookugly.com', 'dsgvo.ru', 'mask03.ru', 'rainbowly.ml', 'beaconmessenger.com', 'yourlms.biz',
    'uu2.ovh', 'mailhex.com', 'allegiancewe.us', 'xxi2.com', 'emaildienst.de', 'sanim.net', '0wnd.org',
    'yopmail.pp.ua', 'us.af', 'delayload.com', 'fosil.pro', 'abusemail.de', 'btizet.pl', 'sly.io',
    'datum2.com', 'icemail.club', 'yhg.biz', 'host1s.com', 'toiea.com', 'stromox.com', 'omail.pro',
    'bidourlnks.com', 'get-mail.cf', 'secured-link.net', 'slothmail.net', 'vercelli.ga', 'acentri.com',
    'nut.cc', 'esiix.com', 'samsclass.info', 'fake-mail.ml', 'ineec.net', 'zomg.info', 'bouncr.com',
    'temp-mails.com', 'crunchcompass.com', 'mailf5.com', 'xxqx3802.com', 'juyouxi.com', 'merry.pink',
    'in-ulm.de', 'mailox.fun', 'sanstr.com', 'fleckens.hu', 'ethereum1.top', 'aa5zy64.com',
    'e-tomarigi.com', 'tinyurl24.com', 'posdz.com', 'wef.gr', 'throwam.com', 'ieh-mail.de',
    'blondemorkin.com', 'freefattymovies.com', 'jobposts.net', 'soioa.com', 'unicodeworld.com',
    'whatiaas.com', 'freecat.net', 'cyber-phone.eu', 'visal168.cf', 'allegrowe.us', 'fasternet.biz',
    'ontyne.biz', 'amadeuswe.us', 'goround.info', 'macromice.info', 'evanfox.info', 'viralplays.com',
    'bgx.ro', 'soombo.com', 'fly-ts.de', 'themostemail.com', 'mt2015.com', 'datenschutz.ru',
    'bcast.ws', 'youpymail.com', 'cellurl.com', 'ucche.us', 'drowblock.com', 'alloywe.us',
    'bluewerks.com', 'jetable.net', 'whiffles.org', 'stuffmail.de', '8mail.ga', 'discard.cf',
    'fuckedupload.com', 'moot.es', 'emailage.ml', 'risu.be', 'mohmal.com', '20minutemail.it',
    '1webmail.info', 'gawab.com', 'odem.com', 'oohioo.com', 'janproz.com', 'istii.ro', 'gynzy.info',
    'fuckme69.club', 'lawlita.com', 'prtnx.com', 'wpdork.com', 'niwl.net', 'polyfaust.net',
    'scatmail.com', 'moimoi.re', 'trgfu.com', 'sofia.re', 'vinernet.com', '1blackmoon.com',
    'fluidsoft.us', 'okrent.us', '300book.info', 'brandallday.net', 'carbtc.net', 'mailt.net',
    'allamericanwe.us', 'top1post.ru', '9mot.ru', 'dev-null.gq', 'zipo1.gq', 'firemailbox.club',
    'ml8.ca', 'cndps.com', 'cosmorph.com', 'muellmail.com', 'jet-renovation.fr', 'mvrht.com',
    'opayq.com', 'skygazerhub.com', 'schafmail.de', 'nolemail.ga', 'fukaru.com', 'tkitc.de',
    'nodezine.com', 'teerest.com', 'broadbandninja.com', 'letmeinonthis.com', 'axsup.net',
    '10minutemail.ga', 'tempemail.co.za', 'squizzy.net', 'amilegit.com', 'oneoffmail.com',
    'binkmail.com', 'gxemail.men', 'guerrillamail.info', 'masonline.info', 'vremonte24-store.ru',
    'moakt.com', 'ckiso.com', 'trashmail.de', '8127ep.com', 'wegwerfemail.net', 'vssms.com',
    'd1yun.com', 'greenhousemail.com', 'anonymousness.com', 'tmpmail.org', 'anonymail.dk',
    'gowikimusic.com', 'xperiae5.com', 'adios.email', 'despammed.com', 'emailspam.tk', 'lackmail.net',
    'wegwerfmail.info', '3trtretgfrfe.tk', 'ultra.fyi', 'filbert4u.com', 'leetmail.co',
    'irishspringrealty.com', 'fastsuzuki.com', 'fake-email.pp.ua', 'primabananen.net',
    'gowikinetwork.com', 'riddermark.de', 'ver0.gq', 'n1nja.org', 'instant-mail.de', 'agilewe.us',
    'abyssmail.com', 'kostenlosemailadresse.de', 'inclusiveprogress.com', 'temp-mail.com',
    'mailpoof.com', 'optimaweb.me', 'smartnator.com', 'mail-card.net', 'moncourrier.fr.nf',
    'sexical.com', 'sim-simka.ru', 'tapchicuoihoi.com', 'porjoton.com', 'tryzoe.com',
    'ordinaryamerican.net', 'frappina.tk', 'scrsot.com', 'eay.jp', 'qibl.at', 'lzoaq.com', 'emailz.gq',
    'sandwhichvideo.com', 'girlsindetention.com', 'spambog.com', '8mail.cf', 'singlespride.com',
    'globaltouron.com', 'email.net', 'i2pmail.org', 'sharedmailbox.org', 'temp-mail.ru', 'akgq701.com',
    'gomail.in', 'c51vsgq.com', 'ovomail.co', 'yxzx.net', 'mihep.com', 'dingbone.com', 'xoxy.net',
    'aoeuhtns.com', 'caseedu.tk', 'oroki.de', 'maboard.com', 'sry.li', 'sylvannet.com',
    'crazespaces.pw', 'kopagas.com', 'hmh.ro', 'moza.pl', 'nezumi.be', 'trash-mail.ga',
    'web-mail.pp.ua', 'indoserver.stream', 'fakeinbox.cf', 'ihateyoualot.info', 'uploadnolimit.com',
    'cc.liamria', 'trayna.com', 'trend-maker.ru', 'wegwerfemail.com', 'agorawe.us', 'illistnoise.com',
    'get-mail.tk', 'damai.webcam', 'neotlozhniy-zaim.ru', 'wanko.be', 'vctel.com', 'freeletter.me',
    'marketlink.info', 'spamtrap.ro', 'visal168.ml', 'umail.net', 'jsrsolutions.com', 'max-mail.org',
    'kurzepost.de', 'tryalert.com', 'x24.com', 'tarzanmail.cf', 'nnot.net', 'thelightningmail.net',
    'quick-mail.cc', 'mepost.pw', 'dm.w3internet.co.uk example.com', 'slaskpost.se', 'owleyes.ch',
    'metalunits.com', 'eintagsmail.de', 'axon7zte.com', 'mr24.co', 'kludgemush.com', 'moeri.org',
    'kismail.ru', 'xjoi.com', 'anon-mail.de', 'web-inc.net', 'spamtrail.com', 'amiriindustries.com',
    'apps.dj', 'turual.com', 'helpjobs.ru', 'mega.zik.dj', 'hopemail.biz', 'mysamp.de',
    'apfelkorps.de', 'notsharingmy.info', 'emailgenerator.de', 'purcell.email', 'mailbox.in.ua',
    'notmailinator.com', 'reconmail.com', 'klick-tipp.us', 'mysugartime.ru', 'p71ce1m.com',
    'totoan.info', 'dhy.cc', 'intopwa.net', 'robertspcrepair.com', '140unichars.com', '24hourmail.com',
    '10minut.xyz', 'midiharmonica.com', 'anappthat.com', 'cuirushi.org', 'chumpstakingdumps.com',
    'outmail.win', 'smapfree24.org', 'stayhome.li', 'emailto.de', 'hidemail.us', 'divad.ga',
    'jetable.org', 'manybrain.com', '12minutemail.net', 'compareshippingrates.org', 'free-temp.net',
    'gynzy.sk', 'spammotel.com', 'valhalladev.com', 'ikbenspamvrij.nl', 'zehnminuten.de', 'teml.net',
    'mailfs.com', 'adiq.eu', 'heros3.com', 'icx.ro', 'topranklist.de', 'mybitti.de', 'telecomix.pl',
    'slopsbox.com', 'mail666.ru', 'postacin.com', '7days-printing.com', 'mailsiphon.com', 'bptfp.net',
    'myzx.com', 'ver0.cf', 'hukkmu.tk', 'disbox.net', 'uroid.com', 'imgv.de', 'haida-edu.cn',
    'l6factors.com', 'sendspamhere.com', 'guerrillamailblock.com', 'knol-power.nl', '1usemail.com',
    '6mail.ml', 'huangniu8.com', 'moy-elektrik.ru', 'zumpul.com', 'dspwebservices.com',
    'domforfb23.tk', 'a45.in', 'habitue.net', 'inbox2.info', 'smapfree24.eu', 'cross-law.gq',
    'instantblingmail.info', 'guerillamail.net', 'mailpick.biz', 'fuckingduh.com', 'karta-kykyruza.ru',
    'mycorneroftheinter.net', 'thc.st', 'wudet.men', 'mail114.net', 'hot-mail.cf', 'mbx.cc',
    'fastmazda.com', 'secure-mail.biz', 'oonies-shoprus.ru', 'wifimaple.com', 'b1of96u.com',
    'fullangle.org', 'ilovespam.com', 'housat.com', 'ginzy.eu', 'vdig.com', 'zombie-hive.com',
    'alchemywe.us', 'macromaid.com', 'pleasenoham.org', 'moreawesomethanyou.com', 'ano-mail.net',
    'fuwa.be', 'mm5.se', 'borged.net', 'funnycodesnippets.com', 'nextmail.info', 'mytempemail.com',
    'spamhereplease.com', 'oerpub.org', 'sausen.com', 'spaminator.de', 'okzk.com', '4057.com',
    'big1.us', 'notif.me', 'emailspam.cf', 'emaildrop.io', 'express.net.ua', 'rollindo.agency',
    'taglead.com', '675hosting.com', 'guerrillamail.net', 'pa9e.com', 'plexolan.de', 'appzily.com',
    'raketenmann.de', 'goatmail.uk', 'trbvn.com', 'wuzupmail.net', 'agendawe.us', 'storj99.com',
    'trash-amil.com', 'mrvpt.com', 'mt2014.com', 'onetm.jp', 'suremail.info', 'lkgn.se',
    'mailbucket.org', 'trashdevil.com', 'meepsheep.eu', 'emailigo.de', 'footard.com', 'spamhole.com',
    'alienware13.com', 'figjs.com', 'arur01.tk', 'dwse.edu.pl', 'my-teddyy.ru', 'zxcv.com',
    'thisurl.website', 'coreclip.com', 'kwilco.net', 'jobs-to-be-done.net', 'myde.ml',
    'ausgefallen.info', 'deadfake.cf', 'mliok.com', '10minutenemail.de', 'mailboxy.fun',
    'mypartyclip.de', 'tqosi.com', 'e3z.de', 'sneakmail.de', 'spamgoes.in', 'xoxox.cc', 'cszbl.com',
    'lenovog4.com', 'cnmsg.net', 'vermutlich.net', 'selfdestructingmail.com', 'amplifiedwe.us',
    'chithinh.com', 'hasanmail.ml', 'instantmail.fr', 'legalrc.loan', 'schachrol.com',
    'wegwerf-email.de', '20mail.eu', 'vaati.org', 'guerillamail.org', 'daryxfox.net', 'lyft.live',
    'bigprofessor.so', 'giantmail.de', 'mcache.net', 'ezehe.com', 'pro5g.com', '4warding.com',
    'foobarbot.net', 'odnorazovoe.ru', 'uuf.me', 'ask-mail.com', 'techemail.com', 'predatorrat.gq',
    'easytrashmail.com', 'cylab.org', 'emailo.pro', 'genderfuck.net', 'oida.icu', 'abuser.eu',
    'iozak.com', 'meinspamschutz.de', 'landmail.co', 'mywarnernet.net', 'mailed.ro', 'spambox.org',
    'agtx.net', 'lazyinbox.us', 'quicksend.ch', 'curryworld.de', 'tourcc.com', 'wilemail.com',
    'gbmail.top', 'ra3.us', 'spamthis.network', 'fyii.de', 'eanok.com', 'kalapi.org',
    'rnailinator.com', 'hidebox.org', 'tempmail.it', 'nezdiro.org', '10mail.com', 'barooko.com',
    'rebates.stream', 'gotmail.org', 'trungtamtoeic.com', 'monachat.tk', 'golemico.com', 'qbfree.us',
    'deadspam.com', 'nekosan.uk', 'stop-my-spam.tk', 'figshot.com', 'promailt.com', 'glucosegrin.com',
    'achievementwe.us', 'zetmail.com', 'ubm.md', 'aeonpsi.com', 'dialogus.com', '4gfdsgfdgfd.tk',
    'emailproxsy.com', 'sejaa.lv', 'txen.de', 'vztc.com', 'getmails.eu', 'zxcvbnm.com', 'candymail.de',
    'punkass.com', 'acceleratewe.us', 'nagi.be', 'pisls.com', 'cdfaq.com', 'zsero.com', 'rklips.com',
    'hulapla.de', '2anom.com', 'kindamail.com', 'kloap.com', 'addictingtrailers.com', 'fantasymail.de',
    'getnada.com', 'web-contact.info', 'inboxed.im', 'ampsylike.com', 'xl.cx', 'appinventor.nl',
    'disbox.org', 'kulturbetrieb.info', 'linshiyouxiang.net', 'kara-turk.net', 'kamen-market.ru',
    'kjkszpjcompany.com', 'midcoastsolutions.com', 'poutineyourface.com', 'purelogistics.org',
    'llogin.ru', 'topmail2.net', 'rtskiya.xyz', 'stumpfwerk.com', 'kyois.com', 'locanto1.club',
    'mountainregionallibrary.net', 'whyspam.me', 'uggsrock.com', 'sidelka-mytischi.ru', 'mailde.info',
    'holl.ga', 'mailmate.com', 'musiccode.me', 'ourpreviewdomain.com', 'p-banlis.ru', 'acceptwe.us',
    'crankhole.com', 'lifetotech.com', 'qtum-ico.com', 'mail0.ga', 'spamfighter.gq', 'ssoia.com',
    'papierkorb.me', 'wegwerf-email.at', 'satukosong.com', 'hotsoup.be', 'jmail.ro', 'wegwrfmail.de',
    'putthisinyourspamdatabase.com', 'mailguard.me', 'royal.net', 'vesa.pw', 'wegwerfemail.org',
    'thunkinator.org', 'fudgerub.com', 'getnowtoday.cf', 'lackmail.ru', 'lillemap.net',
    'otherinbox.com', 'spamdecoy.net', 'prtshr.com', 'mohmal.tech', 'siteposter.net', 'bcaoo.com',
    'teewars.org', 'sweetpotato.ml', 'guerillamail.info', 'trash-mail.at', 'mytempmail.com',
    'kakadua.net', 'pimpedupmyspace.com', 'myspaceinc.com', 'aegiscorp.net', '****mail.me',
    'dammexe.net', 'voltaer.com', 'photo-impact.eu', 'afterhourswe.us', 'proprietativalcea.ro',
    'findemail.info', 'bepureme.com', 'outlawspam.com', 'buyusedlibrarybooks.org', 'showslow.de',
    '10minutemailbox.com', 'totalvista.com', 'forgetmail.com', 'quipas.com', 'emailtemporanea.com',
    'dropmail.me', 'inboxclean.org', 'watchever.biz', 'almondwe.us', 'ro.lt', 'nervtmich.net',
    'shmeriously.com', 'tilien.com', 'freehotmail.net', 'mail-owl.com', 'hackthatbit.ch', 'bareed.ws',
    'leeching.net', 'cs.email', 'ebeschlussbuch.de', 'webemail.me', '9q.ro', 'boxomail.live',
    'fanclub.pm', 'teleworm.us', 'polarkingxx.ml', 'trgovinanaveliko.info', 'kingsq.ga',
    '60minutemail.com', 'acclaimwe.us', 'antireg.ru', 'nekochan.fr', 'vradportal.com', 'hartbot.de',
    'mail-temporaire.fr', 'nada.email', 'mailbiz.biz', 'thrma.com', 'iuemail.men',
    'parlimentpetitioner.tk', 'voxelcore.com', 'myopang.com', 'mailinator1.com', 'eelmail.com',
    'afarek.com', 'no-ux.com', 'tempmail2.com', 'fakemail.io', 'pooae.com', 'imailt.com', 'spybox.de',
    'tefl.ro', 'thismail.net', 'vps911.net', 'bartdevos.be', 'daymail.life', 'jdz.ro',
    'predatorrat.cf', 'monmail.fr.nf', 'vorga.org', 'lpfmgmtltd.com', '9ox.net', '6hjgjhgkilkj.tk',
    'breakthru.com', 'messwiththebestdielikethe.rest', 'akapost.com', 'jajxz.com', 'guerillamail.de',
    'tempinbox.com', 'adeptwe.us', 'dotman.de', 'jpco.org', '2120001.net', 'getover.de',
    'liamcyrus.com', 'qasti.com', 'wegwerfmail.de', 'bdmuzic.pw', 'esprity.com', 'dim-coin.com',
    'at0mik.org', 'submic.com', 'lerbhe.com', 'tokem.co', 'wegwerf-emails.de', 'whopy.com', 'gally.jp',
    'etranquil.com', 'nospamfor.us', 'alivewe.us', 'himail.online', 'mandraghen.cf', '75hosting.net',
    'kmail.live', 'nonze.ro', 'powerencry.com', '12hosting.net', 'odaymail.com', 'spamstack.net',
    'now.im', '10minutemail.nl', 'cloud-mail.top', 'accordwe.us', 'smtp99.com', 'diapaulpainting.com',
    'advantimo.com', 'fag.wf', '30mail.ir', 'ebbob.com', 'ero-tube.org', 'predatorrat.ml',
    'shiftmail.com', 'wg0.com', 'americanawe.us', 'fux0ringduh.com', 'mailblocks.com',
    'mailinator6.com', '5ymail.com', 'mail-tester.com', '12minutemail.com', 'temporaryforwarding.com',
    'slave-auctions.net', 'ushijima1129.gq', 'forward.cat', 'pratikmail.org', 'posta.store',
    'paplease.com', 'akmail.in', 'wallm.com', 'superyp.com', 'ccmail.uk', 'mac-24.com',
    'mailtrash.net', 'hot-mail.ml', 'pakadebu.ga', 'spamthis.co.uk', 'veryday.info', 'disposable.ml',
    'devnullmail.com', 'coin-host.net', 'ethersports.org', 'mytrashmail.com', 'my10minutemail.com',
    'bigwhoop.co.za', '24hourmail.net', 'fukurou.ch', 'soon.it', 'snakemail.com', 'crossroadsmail.com',
    'nospamthanks.info', 'haydoo.com', 'immo-gerance.info', 'hostingmail.me', 'maildax.me',
    'e-mail.org', 'luckymail.org', 'allprowe.us', 'dealja.com', 'temporaryinbox.com',
    'crastination.de', 'mailorg.org', 'ezfill.com', 'lacto.info', 'myinterserver.ml',
    'autorobotica.com', 'eposta.buzz', 'lak.pp.ua', 'receiveee.com', 'emailna.co', 'throya.com',
    'superrito.com', 'lgxscreen.com', 'kademen.com', 'galaxy.tv', 'disposableaddress.com',
    'spamslicer.com', 'boxtemp.com.br', 'emailtemporanea.net', 'sinaite.net', 'reality-concept.club',
    'geronra.com', 'asorent.com', 'predatorrat.ga', 'glubex.com', 'ye.vc', 'twoweirdtricks.com',
    'civikli.com', 'mailtv.tv', 'mxclip.com', 'luv2.us', 'eripo.net', 'psh.me', 'thecity.biz',
    'sendfree.org', 'ahmedkhlef.com', 'car101.pro', 'noclickemail.com', 'victoriantwins.com',
    'mail.wtf', 'daibond.info', 'getonemail.net', 'offshore-proxies.net', 'totesmail.com',
    'walala.org', 'hccmail.win', 'nakedtruth.biz', 'zhcne.com', 'indosukses.press', 'intersteller.com',
    'mvrht.net', 'spam.la', 'asu.mx', 'welikecookies.com', 'wlist.ro', 'visal168.ga', 'pii.at',
    'fake-box.com', 'fr.nf', 'escapehatchapp.com', 'naymedia.com', 'bitwhites.top', 'getonemail.com',
    'anonmail.top', 'junkmail.ga', 'flowu.com', 'bobmail.info', 'norwegischlernen.info', 'afia.pro',
    'spamavert.com', 'kook.ml', 'mailfree.gq', 'youmailr.com', 'mp-j.ga', 'gruz-m.ru', 'cheatmail.de',
    'mail-share.com', 'spamify.com', 'saharanightstempe.com', 'mailquack.com', '7mail.ga',
    'gmxmail.win', 'supermailer.jp', 'webtrip.ch', 'kagi.be', 'qisoa.com', 'tualias.com', 'xemne.com',
    '1-8.biz', 'rmqkr.net', 'yourewronghereswhy.com', 'thembones.com.au', 'morsin.com',
    'weg-werf-email.de', 'allinonewe.us', 'disign-concept.eu', 'americaswe.us', 'kksm.be', '147.cl',
    'ver0.tk', 'iheartspam.org', 'mynetstore.de', 'gsredcross.org', 'crossmailjet.com',
    'omnievents.org', 'crapmail.org', 'stop-my-spam.ga', 'via.tokyo.jp', 'thunderbolt.science',
    'privy-mail.de', 'moruzza.com', 'rdklcrv.xyz', 'emeil.in', 'lukemail.info', 'mailcatch.com',
    'nomail.ga', 'bulrushpress.com', 'sino.tw', 'gynzy.at', 'edinburgh-airporthotels.com', 'spamwc.ga',
    'kpooa.com', 'ohi.tw', 'thietbivanphong.asia', 'ushijima1129.cf', 'foreskin.gq', 'emailate.com',
    'rotaniliam.com', 'bobmurchison.com', 'dispose.it', 'skeefmail.com', 'spamthisplease.com',
    'ohaaa.de', 'oranek.com', 'mailinator.info', 'rcpt.at', 'exdonuts.com', 'bcb.ro', 'gafy.net',
    'hidebusiness.xyz', 'dodgemail.de', 'tempail.com', 'doquier.tk', 'xxolocanto.us', 'mswork.ru',
    'allseasonswe.us', 'dcemail.com', 'topofertasdehoy.com', 'nincsmail.hu', 'premium-mail.fr',
    'mailcker.com', 'andthen.us', 'kvhrs.com', 'disposemymail.com', 'ariaz.jetzt', 'asu.su',
    'opmmedia.ga', 'bladesmail.net', 'mailtemporaire.com', 'watch-harry-potter.com', 'matchpol.net',
    'allowed.org', 'softkey-office.ru', 'dr69.site', '10x9.com', 'kazelink.ml', 'temporarily.de',
    '418.dk', 'vixletdev.com', 'petloca.com', 'netricity.nl', 'gotmail.net', 'dab.ro',
    'suburbanthug.com', 'qiott.com', 'mhzayt.online', 'sohus.cn', 'foreskin.tk', 'lru.me',
    'timgiarevn.com', 'pastebitch.com', '675hosting.org', 'discardmail.de', 'coieo.com', 'boxmail.lol',
    'lr78.com', 'wh4f.org', 'cane.pw', 'alldirectbuy.com', 'emltmp.com', 'cuendita.com',
    'superblohey.com', 'xn--9kq967o.com', 'mailt.top', 'einmalmail.de', 'forspam.net', 'ggmal.ml',
    'maidlow.info', 'recyclemail.dk', 'wegwrfmail.org', '4-n.us', 'hangxomcuatoilatotoro.ml',
    'konultant-jurist.ru', 'mirai.re', 'privatdemail.net', 'dumpandjunk.com', 'ryteto.me',
    'temp-mail.org', 'tmails.net', 'lilo.me', 'spamoff.de', 'abundantwe.us', 'spamfree24.net',
    'senseless-entertainment.com', 'xents.com', 'bij.pl', 'fastsubaru.com', 'acuitywe.us',
    'mailtemp.info', 'nfast.net', 'yopmail.com', 'degradedfun.net', '0clickemail.com',
    'dongqing365.com', 'mailed.in', 'phone-elkey.ru', 'toss.pw', 'z1p.biz', 'sky-inbox.com',
    'shhmail.com', 'bank-opros1.ru', 'emailage.ga', '75hosting.com', 'disposable-email.ml', 'skrx.tk',
    'heisei.be', '10minutemail.gq', 'newfilm24.ru', 'openavz.com', 'unmail.ru', 'digitalsanctuary.com',
    'burstmail.info', '10minutemail.co.za', 'merepost.com', 'mohmal.in', 'btb-notes.com',
    'mailinator.org', 'send22u.info', 'messagebeamer.de', '0nelce.com', 'nevermail.de', 'poofy.org',
    'privymail.de', 'spamcowboy.net', 'trash-mail.ml', 'spamcannon.net', 'furzauflunge.de',
    'sneakemail.com', 'kutakbisajauhjauh.gq', 'zipcatfish.com', 'meidecn.com', 're-gister.com',
    '9me.site', 'gowikigames.com', 'spamherelots.com', 'yuurok.com', 'dodgit.com', 'bugmenever.com',
    'xrho.com', 'ambitiouswe.us', 'hvastudiesucces.nl', 'qiq.us', 'acrylicwe.us', 'trillianpro.com',
    'tqoai.com', 'mywrld.site', 'mydemo.equipment', 'bccto.me', 'zebins.eu', 'logular.com',
    'zhewei88.com', 'letthemeatspam.com', '6somok.ru', 'smapfree24.com', 'rackabzar.com',
    'spamsphere.com', 'richfinances.pw', 'digitalesbusiness.info', 'gynzy.mobi', 'uiu.us',
    'vfemail.net', 'fiifke.de', 'spamkill.info', 'ckaazaza.tk', 'dengekibunko.ga', 'gav0.com',
    'thrott.com', 'vipmail.name', 'hazelnuts4u.com', 'nthrl.com', 'flyinggeek.net', 'tempmail.eu',
    'directmail24.net', 'funnymail.de', 'jeoce.com', 'randomail.io', 'ququb.com', 'email-temp.com',
    'misterpinball.de', 'tempemail.net', 'highbros.org', 'wbdev.tech', 'mx0.wwwnew.eu', 'tempsky.com',
    'wolfsmail.tk', 'ibnuh.bz', 'myemailboxy.com', 'amail.com', 'pp7rvv.com', 'z-o-e-v-a.ru',
    'uyhip.com', 'borged.org', 'nanonym.ch', 'centermail.net', '4nmv.ru', 'flu.cc', 'infocom.zp.ua',
    'magspam.net', 'tempmail.pp.ua', 'veo.kr', 'bugfoo.com', 'qsl.ro', 'garliclife.com',
    'spammer.fail', 'locantofuck.top', 'chalupaurybnicku.cz', 'mailms.com', 'amiri.net',
    'tempomail.fr', 'tmail.io', 'anyalias.com', 'hotprice.co', 'bbbbyyzz.info', 'businessbackend.com',
    'mkpfilm.com', 'clout.wiki', 'ozatvn.com', 'reimondo.com',
    'icantbelieveineedtoexplainthisshit.com', 'thebearshark.com', 'pipemail.space', 'qmrbe.com',
    'exitstageleft.net', 'cuoly.com', 'xwaretech.net', 'emailz.ml', 'trashemails.de', 'jumonji.tk',
    'spamgourmet.com', 'btcmod.com', 'dolphinnet.net', 'tittbit.in', 'domforfb7.tk', 'spamcowboy.org',
    'bodhi.lawlita.com', 'fallinhay.com', 'zasod.com', 'disposable-e.ml', 'na-cat.com', 'jopho.com',
    'instantemailaddress.com', 'dsiay.com', '4mail.ga', 'mailshell.com', 'tosunkaya.com', 'wmail.club',
    'email-lab.com', 'tech69.com', 'puglieisi.com', 'xmaily.com', 'rcasd.com', 'asdasd.nl',
    'dasdasdascyka.tk', 'fasttoyota.com', 'shieldedmail.com', 'allurewe.us', 'zik.dj',
    'emailtemporario.com.br', 'psoxs.com', 'yourspamgoesto.space', 'abcmail.email', 'hiltonvr.com',
    'aver.com', 'codivide.com', 'ethersportz.info', 'ignoremail.com', 'w3internet.co.uk',
    'popesodomy.com', 'quickmail.nl', 'wbml.net', 'uhe2.com', 'tempmailer.com', 'mailshiv.com',
    'geekforex.com', 'ficken.de', 'jellyrolls.com', 'regspaces.tk', 'loapq.com', 'zoemail.com',
    'icznn.com', 'tlpn.org', 'kcrw.de', 'bugmenot.com', 'hwsye.net', 'irssi.tv', 'adaptwe.us',
    'mailtrix.net', 'wee.my', 'xyzfree.net', 'datarca.com', 'ee1.pl', 'ahem.email', 'vevs.de',
    'spamwc.cf', 'bestparadize.com', 'tyhe.ro', 'nobuma.com', 'opp24.com', 'last-chance.pro',
    'sify.com', 'admiralwe.us', 'temporaryemail.net', 'toprumours.com', 'guerrillamail.de',
    'gedmail.win', 'suioe.com', 'worldspace.link', 'bazaaboom.com', 'analyticswe.us', 'donemail.ru',
    'filzmail.com', 'thecloudindex.com', 'amail1.com', 'fastchrysler.com', '4tb.host',
    'risingsuntouch.com', 'protempmail.com', 'alpinewe.us', 'trash2010.com', 'anonbox.net',
    'gcmail.top', 'ginzi.co.uk', 'lifetimefriends.info', 'imperialcnk.com', 'dmarc.ro',
    'slushmail.com', 'hezll.com', 'facebook-email.ml', 'trash-me.com', 'spam4.me', 'chacuo.net',
    'muellemail.com', 'mailinator.gq', 'mailinator8.com', 'cmail.club', 'divismail.ru',
    'classesmail.com', 'dodgit.org', 'netcom.ws', 'mnode.me', 'smellfear.com', 'stathost.net',
    'gishpuppy.com', 'lhsdv.com', 'dump-email.info', 'gowikibooks.com', 'duck2.club', 'affinitywe.us',
    'mamulenok.ru', 'mxfuel.com', 'discard.email', 'rhyta.com', 'pizzajunk.com', 'barryogorman.com',
    'pecinan.net', 'tuofs.com', 'analyticwe.us', 'greggamel.net', 'techgroup.me', 'huskion.net',
    'gynzi.co.uk', 'basscode.org', 'inbound.plus', 'watchironman3onlinefreefullmovie.com',
    'futuramind.com', 'myecho.es', 'rudymail.ml', 'lastmail.com', 'yougotgoated.com', 'dukedish.com',
    'appixie.com', 'iffymedia.com', 'emailcu.icu', 'guerillamail.biz', 'sdvft.com', 'getairmail.ml',
    'onlatedotcom.info', 'saynotospams.com', 'bofthew.com', 'ezztt.com', 'wins.com.br', 'shitmail.de',
    '75hosting.org', 'wetrainbayarea.com', 'mailpress.gq', 'capitalistdilemma.com', 'mzico.com',
    '10minutemail.ml', '5mail.cf', 'kadokawa.gq', 'politikerclub.de', 'garizo.com', 'gekme.com'}
