topic_tags = [
    "technology",
    "science",
    "mathematics",
    "physics",
    "chemistry",
    "biology",
    "astronomy",
    "earth science",
    "environmental science",
    "data science",

    "programming",
    "software",
    "devops",
    "cloud computing",
    "security",
    "ai",
    "machine learning",
    "databases",
    "networking",

    "open source",
    "blockchain",
    "web development",
    "mobile development",
    "game development",
    "embedded systems",
    "operating systems",
    "distributed systems",
    "api design",
    "testing",

    "business",
    "finance",
    "economics",
    "marketing",
    "startups",
    "entrepreneurship",
    "management",
    "e-commerce",
    "investing",
    "real estate",

    "sales",
    "customer success",
    "product management",
    "operations",
    "supply chain",
    "human resources",
    "leadership",
    "strategy",
    "innovation",
    "consulting",

    "politics",
    "law",
    "education",
    "philosophy",
    "psychology",
    "sociology",
    "history",
    "culture",
    "ethics",
    "religion",

    "geography",
    "anthropology",
    "linguistics",
    "media studies",
    "international relations",
    "public policy",
    "journalism",
    "communication",
    "demographics",
    "urban studies",

    "health",
    "fitness",
    "nutrition",
    "mental health",
    "medicine",
    "public health",
    "wellness",
    "sports",
    "yoga",
    "meditation",

    "travel",
    "food",
    "cooking",
    "recipes",
    "relationships",
    "parenting",
    "personal development",
    "productivity",
    "self improvement",
    "lifestyle",

    "hobbies",
    "diy",
    "crafts",
    "gardening",
    "interior design",
    "fashion",
    "beauty",
    "shopping",
    "sustainability",

    "movies",
    "tv",
    "music",
    "gaming",
    "books",
    "art",
    "photography",
    "design",
    "animation",
    "celebrities",

    "issue",
    "meeting",
    "conference",
    "social life",
    "alert",
    "deadline",
    "urgent",

    "documentation",
    "invoice"
]